name: fuzz-ci

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

  pull_request:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

jobs:
  clang_tests:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-latest

    name: "Fuzzing"

    container:
      image: silkeh/clang:15
      options: -v /usr/local:/host_usr_local

    env:
      CC: clang
      CXX: clang++
      CXXFLAGS: -stdlib=libc++

    steps:
      - uses: actions/checkout@v1

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git
          script/ci_install_deps.sh

      - name: Build
        working-directory: fuzz
        run: make

      - name: Run
        working-directory: fuzz
        run: ssp_fuz -max_total_time=30
